title: Aditya Rastogi # your name (or website title) here
logo: "/images/pciture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Student, Medical Imaging Group
  <br>
  Department of Computation and Data Science
  <br>
  Indian Institute of Sciences
  <br><br>
  B.Tech, Mechanical Engineering
  <br>
  Delhi Technological University
  <br>
  2012-2016
  <br>
  <br>
  Page template forked from <a href="https://github.com/evanca/quick-portfolio">evanca</a>

  
theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
