title: Aditya Rastogi # your name (or website title) here
logo: "/images/pciture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Student, Medical Imaging Group
  <br>
  Department of Computation and Data Science
  <br>
  Indian Institute of Sciences
  <br><br>
  Second description 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
