title: Aditya Rastogi, PhD # your name (or website title) here
logo: "/images/aditya_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Post Doctoral Researcher, Department of Neuroradiology 
  <br>
  Universitätsklinikum Bonn, Germany
  <br><br>
  PhD, Medical Imaging Group
  <br>
  Department of Computational and Data Science
  <br>
  Indian Institute of Science
  <br><br>
  B.Tech, Mechanical Engineering
  <br>
  Delhi Technological University
  <br>
  2012-2016
show_downloads: true
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

